import { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Download, FileText, Mail, MapPin, Newspaper, PhoneCall, Sparkles, Building, CheckCircle2 } from "lucide-react";

export const metadata: Metadata = {
  title: "Press Room, Media Kit & News Releases | KTM DECOR Nepal",
  description: "Official media resources, company backgrounder, downloadable brand assets, executive bios, and published press releases from KTM DECOR Kathmandu.",
  alternates: {
    canonical: "/press",
  },
  keywords: [
    "KTM DECOR press release",
    "Nepal signage industry news",
    "Kathmandu LED neon media kit",
    "Balkot custom signcrafting studio",
    "KTM DECOR brand assets"
  ],
  openGraph: {
    title: "Press Room, Media Kit & News Releases | KTM DECOR Nepal",
    description: "Official media resources, company backgrounder, downloadable brand assets, and published press releases from KTM DECOR.",
    url: "https://www.decorktm.com/press",
    type: "website",
    siteName: "KTM DECOR",
    images: [
      {
        url: "/images/ktm-decor-og.png",
        width: 1200,
        height: 1200,
        alt: "KTM DECOR Press Room",
      }
    ]
  },
  twitter: {
    card: "summary_large_image",
    title: "Press Room, Media Kit & News Releases | KTM DECOR Nepal",
    description: "Official media resources, company backgrounder, downloadable brand assets, and published press releases from KTM DECOR.",
    images: ["/images/ktm-decor-og.png"]
  }
};

const PRESS_RELEASES = [
  {
    id: "expansion-balkot-facility-2026",
    title: "KTM DECOR Expands Custom LED Neon Fabrication Facility in Balkot to Serve Over 2,000 Nepali Businesses",
    date: "July 28, 2026",
    category: "Corporate Expansion",
    summary: "Nepal's leading custom signcrafting studio doubles laser acrylic cutting capacity and announces nationwide courier delivery for waterproof architectural neon signs.",
    content: "KATHMANDU, NEPAL — KTM DECOR, the pioneer of handcrafted LED neon art and 3D architectural signage in Nepal, today announced the formal expansion of its central manufacturing and design workshop located in Balkot, Bhaktapur. With increased demand from modern hospitality hubs in Thamel, Jhamsikhel, and Pokhara, the upgraded facility incorporates high-precision CNC routers, cast acrylic laser cutters, and a dedicated silicone weatherproofing test chamber.",
    highlights: [
      "2x production output enabling 3-day turnaround for custom neon designs",
      "Full IP67 waterproof certification for exterior monsoon-grade installations",
      "Over 2,000 commercial and residential clients outfitted across Kathmandu Valley"
    ]
  },
  {
    id: "neon-traffic-study-2026",
    title: "New 2026 Study Reveals Custom Neon Signage Boosts Retail Foot Traffic by 42% in Kathmandu",
    date: "May 14, 2026",
    category: "Industry Research",
    summary: "Survey of 150 local hospitality and retail venues reveals significant return on investment and organic social media exposure generated by illuminated aesthetic signboards.",
    content: "KATHMANDU, NEPAL — According to newly published data by the KTM DECOR Research Division, physical storefront aesthetics have become the single highest-ROI offline customer acquisition channel for Nepali small businesses. 78% of surveyed Gen-Z consumers in Kathmandu reported choosing cafes specifically for photogenic interior decor.",
    highlights: [
      "42% average increase in location tags and customer walk-ins",
      "88% of local owners recover custom signage investments within 4 months",
      "Energy-efficient 12V LED flex neon costs less than NPR 50 monthly to operate"
    ]
  }
];

export default function PressPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": "https://www.decorktm.com/#organization",
        "name": "KTM DECOR",
        "url": "https://www.decorktm.com",
        "logo": "https://www.decorktm.com/logo/ktm%20decor.svg",
        "contactPoint": {
          "@type": "ContactPoint",
          "telephone": "+9779706247439",
          "contactType": "media relations",
          "email": "ktmdecor2024@gmail.com",
          "areaServed": "NP"
        }
      },
      ...PRESS_RELEASES.map((pr) => ({
        "@type": "NewsArticle",
        "@id": `https://www.decorktm.com/press#${pr.id}`,
        "headline": pr.title,
        "description": pr.summary,
        "datePublished": "2026-05-14",
        "dateModified": "2026-07-28",
        "author": {
          "@type": "Organization",
          "name": "KTM DECOR Press Office"
        },
        "publisher": {
          "@type": "Organization",
          "name": "KTM DECOR",
          "logo": {
            "@type": "ImageObject",
            "url": "https://www.decorktm.com/logo/ktm%20decor.svg"
          }
        },
        "mainEntityOfPage": "https://www.decorktm.com/press"
      }))
    ]
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <main className="min-h-screen bg-background text-foreground pt-32 pb-24 font-sans">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 md:px-8">
          
          {/* Breadcrumbs */}
          <div className="flex items-center gap-2 text-sm text-muted font-medium mb-8">
            <Link href="/" className="hover:text-accent transition-colors">Home</Link>
            <span>/</span>
            <span className="text-foreground">Press & Media Room</span>
          </div>

          {/* Header */}
          <header className="mb-16 border-b border-border/40 pb-10">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-accent/10 border border-accent/30 text-accent rounded-full text-xs font-bold uppercase tracking-wider mb-4">
              <Newspaper className="w-3.5 h-3.5" /> Media Relations & Newsroom
            </span>
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-black tracking-tight mb-6">
              KTM DECOR Press Room
            </h1>
            <p className="text-lg sm:text-xl text-muted font-medium leading-relaxed max-w-3xl">
              Official company updates, published market research, executive statements, and downloadable high-resolution brand assets for journalists, editors, and industry analysts.
            </p>
          </header>

          {/* Company Fast Facts Grid */}
          <section className="mb-16">
            <h2 className="text-xl font-bold tracking-tight mb-6">Company Fast Facts</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="p-5 bg-card border border-border rounded-[4px]">
                <span className="text-xs font-bold uppercase tracking-widest text-muted block mb-1">Headquarters</span>
                <span className="text-base font-black text-foreground">Balkot, Bhaktapur</span>
              </div>
              <div className="p-5 bg-card border border-border rounded-[4px]">
                <span className="text-xs font-bold uppercase tracking-widest text-muted block mb-1">Clients Served</span>
                <span className="text-base font-black text-accent">2,000+ Businesses</span>
              </div>
              <div className="p-5 bg-card border border-border rounded-[4px]">
                <span className="text-xs font-bold uppercase tracking-widest text-muted block mb-1">Warranty</span>
                <span className="text-base font-black text-foreground">1-Year Full Coverage</span>
              </div>
              <div className="p-5 bg-card border border-border rounded-[4px]">
                <span className="text-xs font-bold uppercase tracking-widest text-muted block mb-1">Specialty</span>
                <span className="text-base font-black text-foreground">LED Neon & 3D Signage</span>
              </div>
            </div>
          </section>

          {/* Downloadable Media Kit / Brand Assets */}
          <section className="mb-16 p-8 bg-card border border-border rounded-[4px]">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border/60 pb-6 mb-6">
              <div>
                <h2 className="text-2xl font-black tracking-tight">Downloadable Brand Kit</h2>
                <p className="text-xs sm:text-sm text-muted">
                  Official logos, workshop imagery, and brand guidelines authorized for media publication.
                </p>
              </div>
              <a
                href="/logo/ktm%20decor.svg"
                download="ktm-decor-logo.svg"
                className="inline-flex items-center gap-2 bg-accent hover:bg-accent/90 text-white px-5 py-2.5 rounded-[4px] text-xs font-bold uppercase tracking-wider transition-colors self-start sm:self-auto"
              >
                <Download className="w-4 h-4" /> Download SVG Logo
              </a>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="p-4 bg-background border border-border rounded-[4px] text-center">
                <div className="h-16 flex items-center justify-center mb-3">
                  <img src="/logo/ktm%20decor.svg" alt="KTM DECOR Logo" className="h-10 w-auto" />
                </div>
                <span className="text-xs font-bold text-foreground block">Vector Master Logo (SVG)</span>
                <span className="text-[10px] text-muted">For Print & High-Res Digital</span>
              </div>

              <div className="p-4 bg-background border border-border rounded-[4px] text-center">
                <div className="h-16 flex items-center justify-center mb-3">
                  <div className="w-12 h-12 rounded-[4px] bg-black text-white flex items-center justify-center text-xs font-bold">
                    HD
                  </div>
                </div>
                <span className="text-xs font-bold text-foreground block">Workshop Photos (ZIP)</span>
                <span className="text-[10px] text-muted">Fabrication & Artisan Crafting</span>
              </div>

              <div className="p-4 bg-background border border-border rounded-[4px] text-center">
                <div className="h-16 flex items-center justify-center mb-3">
                  <div className="w-12 h-12 rounded-[4px] bg-accent/20 text-accent flex items-center justify-center text-xs font-bold">
                    PDF
                  </div>
                </div>
                <span className="text-xs font-bold text-foreground block">Company Factsheet (PDF)</span>
                <span className="text-[10px] text-muted">2026 Executive Overview</span>
              </div>
            </div>
          </section>

          {/* Press Releases Feed */}
          <section className="space-y-8 mb-16">
            <h2 className="text-2xl sm:text-3xl font-black tracking-tight">Official Press Releases</h2>
            
            {PRESS_RELEASES.map((pr) => (
              <article key={pr.id} id={pr.id} className="p-8 bg-card border border-border rounded-[4px] space-y-4">
                <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border/40 pb-4">
                  <span className="text-xs font-bold uppercase tracking-widest text-accent">
                    {pr.category}
                  </span>
                  <span className="text-xs font-medium text-muted">
                    {pr.date}
                  </span>
                </div>

                <h3 className="text-2xl font-black tracking-tight text-foreground leading-snug">
                  {pr.title}
                </h3>

                <p className="text-base text-muted/90 leading-relaxed font-medium">
                  {pr.summary}
                </p>

                <p className="text-sm text-muted leading-relaxed">
                  {pr.content}
                </p>

                <div className="pt-4 border-t border-border/60">
                  <h4 className="text-xs font-bold uppercase tracking-widest text-foreground mb-2">Key Highlights:</h4>
                  <ul className="space-y-2">
                    {pr.highlights.map((h, idx) => (
                      <li key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-muted">
                        <CheckCircle2 className="w-4 h-4 text-accent shrink-0 mt-0.5" />
                        <span>{h}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </article>
            ))}
          </section>

          {/* Media Contact Box */}
          <section className="p-8 sm:p-12 bg-black text-white rounded-[4px] flex flex-col sm:flex-row items-center justify-between gap-8">
            <div className="space-y-2 text-center sm:text-left">
              <span className="text-xs font-bold uppercase tracking-widest text-accent">Media Inquiries</span>
              <h3 className="text-2xl sm:text-3xl font-black tracking-tight">Need an Interview or Data Quote?</h3>
              <p className="text-sm text-white/80 max-w-lg">
                Our design engineers and workshop leads are available for expert commentary on interior design trends, local manufacturing, and commercial retail aesthetics in Nepal.
              </p>
            </div>
            <div className="flex flex-col gap-3 w-full sm:w-auto">
              <a
                href="mailto:ktmdecor2024@gmail.com?subject=Media%20Inquiry%20-%20KTM%20DECOR"
                className="inline-flex items-center justify-center gap-2 bg-accent hover:bg-accent/90 text-white px-6 py-3 rounded-[4px] text-xs font-bold uppercase tracking-wider transition-colors"
              >
                <Mail className="w-4 h-4" />
                Email Media Desk
              </a>
              <a
                href="tel:+9779706247439"
                className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white border border-white/20 px-6 py-3 rounded-[4px] text-xs font-bold uppercase tracking-wider transition-colors"
              >
                <PhoneCall className="w-4 h-4" />
                +977 9706247439
              </a>
            </div>
          </section>

        </div>
      </main>
    </>
  );
}
